version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
#      - 51773
# actual SuperSever Port
      - 1972
      - 52773
      - 53773
    volumes:
# no license require dfor community image
#     - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
